"""Type stubs for bitmap_handler module."""
import logging
from typing import Dict, List, Optional, Union

class BitmapHandler:
    logger: logging.Logger
    bitmap: Dict[str, int]
    key_list: List[str]
    def __init__(self, keys: List[str], logger: Optional[logging.Logger] = None) -> None: ...
    def get_bitkey(self, *args: str) -> int: ...
    def check_key_in_bitkey(self, key: str, bitkey: int) -> bool: ...
    def get_active_keys(self, bitkey: int, single: bool = False) -> Union[str, List[str]]: ...
    def toggle_key_in_bitkey(self, key: str, bitkey: int, add: bool = True) -> int: ...
    def invert_bitkey(self, bitkey: int) -> int: ...
    def count_active_bits(self, bitkey: int) -> int: ...
    def compare_bitkeys(self, bitkey1: int, bitkey2: int) -> Dict[str, List[str]]: ...
    def add_key(self, key: str) -> None: ...
    def remove_key(self, key: str) -> None: ...
    def get_keys(self) -> Dict[str, int]: ...
