"""Type stubs for googletrans module."""
import logging
from typing import Any, Optional

class API:
    credentials_path: str
    translate_client: Any
    logger: logging.Logger
    def __init__(self, credentials_path: str, logger: Optional[logging.Logger] = None) -> None: ...
    def translate_text(self, text: str, target_language: str, source_language: str = "") -> str: ...
    def check_credentials(self) -> bool: ...
    def get_languages(self) -> dict: ...
    def detect_language(self, text: str) -> str: ...
