"""Type stubs for libretrans module."""
import logging
from typing import Any, Optional

class Errors:
    class InvalidAPIKey(Exception): ...
    class BadRequest(Exception): ...
    class Forbidden(Exception): ...
    class RateLimitExceeded(Exception): ...
    class InternalServerError(Exception): ...

class API:
    api_key: str
    url: str
    logger: logging.Logger
    def __init__(self, api_key: str, url: str, logger: Optional[logging.Logger] = None) -> None: ...
    async def detect(self, text: str) -> dict: ...
    async def translate(
        self,
        text: str,
        target_language: str,
        source_language: str = "",
        is_file: bool = False,
    ) -> str: ...
    async def get_languages(self) -> dict: ...
