"""Type stubs for patchnotes module."""
import logging
from typing import Optional

def set_logger(logger: Optional[logging.Logger] = None) -> None: ...
async def get_update_content(version: str, return_type: str = "html") -> Optional[str]: ...
async def get_latest_update(return_type: str = "html") -> Optional[str]: ...
