"""Type stubs for steam module."""
import logging
from typing import Optional, Union

class Errors:
    class Private(Exception):
        def __init__(self, message: str = "This profile is private.") -> None: ...
    class RateLimit(Exception):
        def __init__(self, message: str = "Rate limit exceeded.") -> None: ...
    class InvalidKey(Exception):
        def __init__(self, message: str = "Invalid key.") -> None: ...

class API:
    ERR_INVALID_STEAMID: str
    KEY: str
    def __init__(self, key: str, logger: Optional[logging.Logger] = None) -> None: ...
    async def key_is_valid(self) -> bool: ...
    async def get_player_summeries(self, steamid: str) -> dict: ...
    async def get_player_achievements(self, steamid: str, appid: int) -> dict: ...
    async def link_to_id(self, link: str) -> Optional[str]: ...
    async def owns_game(self, steamid: str, appid: int) -> Union[bool, dict]: ...
    async def get_app_details(self, appid: int) -> dict: ...

async def get_free_promotions() -> Union[list, dict]: ...
